### ISSUE TITLE
Issue in the Makefile

### ISSUE THREAD

**Issue by mrLarbi** [CharlesHD/linkstream#1]
Bonjour Charles,

Je suis étudiant de Binh Minh à l'UPMC pour le module AAGA. On a utilisé le programme linkstream, il y'a néanmoins une petite erreur dans le Makefile, en effet la ligne : 

install: all
    cp target/release/linkstreams /usr/bin/linkstream

devrait être : 

install: all
    cp target/release/linkstream /usr/bin/linkstream

(Il y'a un s en trop dans l'executable)

Bonne journée !

**Comment by CharlesHD** [comment]
Wow, effectivement. C'est une incohérence qui traîne depuis des lustres ! 
Je corrige ça. Ça doit trainer dans tout un tas de fichiers de scripts. Merci de l'avoir pointée !

Edit : Ah c'est dans la commande d'installation. Je m'en suis jamais servi. Du coup c'est tout bête.
